FROM puiterwijk.org/development/base
MAINTAINER Patrick Uiterwijk <patrick@puiterwijk.org>

RUN dnf install -y autoconf automake make gcc fedora-packager python-nss \
                   python-sqlalchemy rpm-sign ostree-devel python-pexpect \
                   psmisc gnupg skopeo
