FROM puiterwijk.org/development/base
MAINTAINER Patrick Uiterwijk <patrick@puiterwijk.org>

RUN dnf install -y python-cryptography python-flask python-fedora python-openid \
                   python-openid-cla python-openid-teams python-sqlalchemy \
                   python-virtualenvwrapper
