FROM puiterwijk.org/development/base
MAINTAINER Patrick Uiterwijk <patrick@puiterwijk.org>

RUN dnf install -y python2-devel python-setuptools python-nose py-bcrypt python-alembic \
                   python-arrow python-binaryornot python-bleach python-blinker \
                   python-chardet python-cryptography python-docutils python-flask \
                   python-flask-wtf python-flask-multistatic python-markdown python-psutil \
                   python-pygit2 python-pygments python-fedora python-openid python-openid-cla \
                   python-openid-teams python-straight-plugin python-wtforms python-munch \
                   python-enum34 python-redis python-sqlalchemy systemd gitolite3

RUN dnf install -y python-fedora-flask python-mock
