FROM puiterwijk.org/development/base
MAINTAINER Patrick Uiterwijk <patrick@puiterwijk.org>

RUN dnf install -y fedora-review fedora-packager python-fedora python2-openidc-client python3-openidc-client

RUN usermod -aG mock docker
